disabled = false
languageCode = "ru"
languageName = "Russian"
weight = 2
title = "The Alium"

[params]
  displayName = "Русский"
  isoCode = "ru"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Алиумское сообщество — это интернациональная группа игроков и разработчиков в Garry's Mod."
  copyright = "Copy, _right?_ :thinking_face:"
