disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "The Alium"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "Copy, _right?_ :thinking_face:"
