disabled = false
languageCode = "uk"
languageName = "Ukrainian"
weight = 3
title = "The Alium"

[params]
  displayName = "Український"
  isoCode = "uk"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "Copy, _right?_ :thinking_face:"
