# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# [[main]]
#  name = "Posts"
#  pageRef = "posts"
#  weight = 10

[[main]]
  name = "Main"
  weight = 10
  pageRef = "/"

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Categories"
  parent = "Posts"
  pageRef = "categories"
  weight = 10

[[main]]
  name = "Tags"
  parent = "Posts"
  pageRef = "tags"
  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "RSS"
  pre = "rss"
  url = "/index.xml"
  weight = 10

[[footer]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/The-Alium"
  weight = 20

[[footer]]
  pre = "steam"
  name = "Steam"
  url = "https://steamcommunity.com/groups/thealium"
  weight = 30

[[footer]]
  pre = "discord"
  name = "Discord"
  url = "https://discord.gg/BmQSQEm8GW"
  weight = 40

[[footer]]
  pre = "youtube"
  name = "YouTube"
  url = "https://www.youtube.com/@aliumculture"
  weight = 50
